services:
  ros_noetic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gym_gezebo-container
    image: gym_gazebo-20-noetic:latestcd
    environment:
      # Linux
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY} # not sure if this is actually needed

      # Windows 10/11 using WSLg (part of WSL2)
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - PULSE_SERVER

      # ROS pieces
      # - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      # - ROS_LOCALHOST_ONLY=1
      #- RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      #- CYCLONEDDS_URI=file:///home/user/IEA_Target_Tracking/cd ~docker/rtk_cyclonedds.xml
    volumes:
      # The repository files and the bashrc file
      - ./:/home/root/gym_gazebo_docker
      - ./docker/.bashrc:/home/root/.bashrc

      # Windows Display forwarding
      #- /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

      # Other folders you may want to volume in
      #- /home/$USER/.ros/:/home/user/.ros/
      - /home/wizard/models/:/home/root/models/

    working_dir: /home/root/gym_gazebo_docker
    privileged: true
    network_mode: host
    ipc: host

    # group_add: # If you need to add docker user to a group
    #   - ${SHARED_GROUP:-1004}
    
    deploy: # uncomment this if you want to use GPU (only needed for cuda/neural nets)
      resources:
        reservations:
          devices:
           - driver: nvidia
             count: 1
             capabilities: [gpu]
    command: ["bash"]
